import json, re

d = json.load(open('exercises_raw.json'))

ES = {
 "3_4_Sit-Up": "Abdominales 3/4",
 "Ab_Crunch_Machine": "Crunch en máquina",
 "Air_Bike": "Bicicleta en el aire (abdominales)",
 "Alternate_Hammer_Curl": "Curl martillo alterno",
 "Alternate_Incline_Dumbbell_Curl": "Curl alterno con mancuernas en banco inclinado",
 "Arnold_Dumbbell_Press": "Press Arnold",
 "Barbell_Ab_Rollout": "Rueda abdominal con barra",
 "Barbell_Bench_Press_-_Medium_Grip": "Press de banca con barra",
 "Barbell_Curl": "Curl de bíceps con barra",
 "Barbell_Deadlift": "Peso muerto con barra",
 "Barbell_Full_Squat": "Sentadilla profunda con barra",
 "Barbell_Glute_Bridge": "Puente de glúteo con barra",
 "Barbell_Hack_Squat": "Sentadilla hack con barra",
 "Barbell_Hip_Thrust": "Hip thrust con barra",
 "Barbell_Incline_Bench_Press_-_Medium_Grip": "Press inclinado con barra",
 "Barbell_Lunge": "Zancadas con barra",
 "Barbell_Rear_Delt_Row": "Remo con barra para deltoides posterior",
 "Barbell_Seated_Calf_Raise": "Elevación de gemelos sentado con barra",
 "Barbell_Shoulder_Press": "Press de hombros con barra",
 "Barbell_Shrug": "Encogimientos con barra",
 "Barbell_Squat": "Sentadilla con barra",
 "Barbell_Step_Ups": "Subidas al cajón con barra",
 "Barbell_Walking_Lunge": "Zancadas caminando con barra",
 "Bench_Dips": "Fondos en banco",
 "Bench_Press_-_Powerlifting": "Press de banca (powerlifting)",
 "Bent-Arm_Dumbbell_Pullover": "Pullover con mancuerna",
 "Bent-Knee_Hip_Raise": "Elevación de cadera con rodillas flexionadas",
 "Bent_Over_Barbell_Row": "Remo con barra inclinado",
 "Bent_Over_Two-Dumbbell_Row": "Remo con dos mancuernas inclinado",
 "Bicycling_Stationary": "Bicicleta estática",
 "Bodyweight_Squat": "Sentadilla con peso corporal",
 "Bodyweight_Walking_Lunge": "Zancadas caminando",
 "Box_Squat": "Sentadilla al cajón",
 "Butterfly": "Contractora de pecho (pec deck)",
 "Cable_Chest_Press": "Press de pecho en polea",
 "Cable_Crossover": "Cruces en polea",
 "Cable_Crunch": "Crunch en polea",
 "Cable_Hammer_Curls_-_Rope_Attachment": "Curl martillo en polea con cuerda",
 "Cable_Rope_Overhead_Triceps_Extension": "Extensión de tríceps sobre la cabeza en polea con cuerda",
 "Cable_Rear_Delt_Fly": "Aperturas posteriores en polea",
 "Cable_Seated_Lateral_Raise": "Elevaciones laterales en polea sentado",
 "Cable_Shoulder_Press": "Press de hombros en polea",
 "Cable_Shrugs": "Encogimientos en polea",
 "Calf_Press_On_The_Leg_Press_Machine": "Gemelos en prensa",
 "Chin-Up": "Dominadas supinas",
 "Clean_and_Press": "Cargada y press",
 "Close-Grip_Barbell_Bench_Press": "Press de banca agarre cerrado",
 "Close-Grip_EZ_Bar_Curl": "Curl con barra Z agarre cerrado",
 "Close-Grip_Front_Lat_Pulldown": "Jalón al pecho agarre cerrado",
 "Concentration_Curls": "Curl concentrado",
 "Cross-Body_Crunch": "Crunch cruzado",
 "Crunches": "Crunch abdominal",
 "Dead_Bug": "Dead bug",
 "Decline_Barbell_Bench_Press": "Press declinado con barra",
 "Decline_Crunch": "Crunch en banco declinado",
 "Decline_Dumbbell_Bench_Press": "Press declinado con mancuernas",
 "Decline_Push-Up": "Flexiones declinadas",
 "Dip_Machine": "Fondos en máquina",
 "Dips_-_Triceps_Version": "Fondos en paralelas (tríceps)",
 "Dumbbell_Alternate_Bicep_Curl": "Curl alterno con mancuernas",
 "Dumbbell_Bench_Press": "Press de banca con mancuernas",
 "Dumbbell_Bicep_Curl": "Curl de bíceps con mancuernas",
 "Dumbbell_Flyes": "Aperturas con mancuernas",
 "Dumbbell_Lunges": "Zancadas con mancuernas",
 "Dumbbell_One-Arm_Shoulder_Press": "Press de hombro a una mano con mancuerna",
 "Dumbbell_One-Arm_Triceps_Extension": "Extensión de tríceps a una mano con mancuerna",
 "Dumbbell_Rear_Lunge": "Zancada atrás con mancuernas",
 "Dumbbell_Shoulder_Press": "Press de hombros con mancuernas",
 "Dumbbell_Shrug": "Encogimientos con mancuernas",
 "Dumbbell_Squat": "Sentadilla con mancuernas",
 "Dumbbell_Step_Ups": "Subidas al cajón con mancuernas",
 "EZ-Bar_Curl": "Curl con barra Z",
 "EZ-Bar_Skullcrusher": "Press francés con barra Z",
 "Elliptical_Trainer": "Elíptica",
 "Face_Pull": "Face pull",
 "Flat_Bench_Cable_Flyes": "Aperturas en polea en banco plano",
 "Flat_Bench_Lying_Leg_Raise": "Elevación de piernas en banco",
 "Floor_Press": "Press en el suelo",
 "Flutter_Kicks": "Patadas de tijera",
 "Front_Barbell_Squat": "Sentadilla frontal con barra",
 "Front_Dumbbell_Raise": "Elevaciones frontales con mancuernas",
 "Front_Cable_Raise": "Elevaciones frontales en polea",
 "Full_Range-Of-Motion_Lat_Pulldown": "Jalón al pecho rango completo",
 "Glute_Ham_Raise": "Glute ham raise",
 "Glute_Kickback": "Patada de glúteo",
 "Goblet_Squat": "Sentadilla goblet",
 "Good_Morning": "Buenos días con barra",
 "Hack_Squat": "Sentadilla hack en máquina",
 "Hammer_Curls": "Curl martillo",
 "Handstand_Push-Ups": "Flexiones en pino",
 "Hanging_Leg_Raise": "Elevación de piernas colgado",
 "Hyperextensions_With_No_Hyperextension_Bench": "Hiperextensiones en el suelo",
 "Incline_Dumbbell_Curl": "Curl inclinado con mancuernas",
 "Incline_Dumbbell_Flyes": "Aperturas inclinadas con mancuernas",
 "Incline_Dumbbell_Press": "Press inclinado con mancuernas",
 "Incline_Hammer_Curls": "Curl martillo inclinado",
 "Incline_Push-Up": "Flexiones inclinadas",
 "Incline_Cable_Flye": "Aperturas inclinadas en polea",
 "Inverted_Row": "Remo invertido",
 "Jogging_Treadmill": "Trote en cinta",
 "Kettlebell_Pistol_Squat": "Sentadilla pistol con kettlebell",
 "Kettlebell_Thruster": "Thruster con kettlebell",
 "Kettlebell_Windmill": "Molino con kettlebell",
 "Kneeling_Cable_Triceps_Extension": "Extensión de tríceps en polea de rodillas",
 "Leg_Extensions": "Extensión de cuádriceps en máquina",
 "Leg_Press": "Prensa de piernas",
 "Leg_Pull-In": "Encogimientos de piernas sentado",
 "Leverage_Chest_Press": "Press de pecho en máquina (palanca)",
 "Leverage_High_Row": "Remo alto en máquina",
 "Leverage_Iso_Row": "Remo en máquina (iso)",
 "Leverage_Shoulder_Press": "Press de hombros en máquina",
 "Low_Cable_Crossover": "Cruces en polea baja",
 "Lying_Dumbbell_Tricep_Extension": "Extensión de tríceps tumbado con mancuernas",
 "Lying_Leg_Curls": "Curl femoral tumbado",
 "Lying_T-Bar_Row": "Remo en T tumbado",
 "Lying_Triceps_Press": "Press francés (skullcrusher)",
 "Machine_Bench_Press": "Press de banca en máquina",
 "Machine_Bicep_Curl": "Curl de bíceps en máquina",
 "Machine_Preacher_Curls": "Curl predicador en máquina",
 "Machine_Shoulder_Military_Press": "Press militar en máquina",
 "Machine_Triceps_Extension": "Extensión de tríceps en máquina",
 "Oblique_Crunches": "Crunch oblicuo",
 "One-Arm_Dumbbell_Row": "Remo a una mano con mancuerna",
 "One-Arm_Kettlebell_Swings": "Swing con kettlebell a una mano",
 "One-Arm_Side_Laterals": "Elevaciones laterales a una mano",
 "One-Legged_Cable_Kickback": "Patada de glúteo en polea",
 "One_Arm_Lat_Pulldown": "Jalón a una mano",
 "Pallof_Press": "Press Pallof",
 "Plank": "Plancha",
 "Plie_Dumbbell_Squat": "Sentadilla sumo con mancuerna",
 "Power_Clean": "Cargada de potencia",
 "Preacher_Curl": "Curl predicador",
 "Pull_Through": "Pull through en polea",
 "Pullups": "Dominadas",
 "Push-Up_Wide": "Flexiones agarre ancho",
 "Push-Ups_-_Close_Triceps_Position": "Flexiones cerradas (tríceps)",
 "Push_Up_to_Side_Plank": "Flexión a plancha lateral",
 "Pushups": "Flexiones",
 "Rack_Pulls": "Peso muerto desde rack",
 "Recumbent_Bike": "Bicicleta reclinada",
 "Reverse_Barbell_Curl": "Curl inverso con barra",
 "Reverse_Crunch": "Crunch inverso",
 "Reverse_Flyes": "Aperturas invertidas (pájaros)",
 "Reverse_Grip_Bent-Over_Rows": "Remo inclinado agarre supino",
 "Reverse_Grip_Triceps_Pushdown": "Extensión de tríceps en polea agarre supino",
 "Reverse_Hyperextension": "Hiperextensión inversa",
 "Reverse_Machine_Flyes": "Aperturas invertidas en máquina",
 "Romanian_Deadlift": "Peso muerto rumano",
 "Rope_Crunch": "Crunch con cuerda en polea",
 "Rope_Straight-Arm_Pulldown": "Pullover en polea con cuerda",
 "Rowing_Stationary": "Remo (máquina)",
 "Running_Treadmill": "Correr en cinta",
 "Russian_Twist": "Giro ruso",
 "Scapular_Pull-Up": "Dominada escapular",
 "Seated_Barbell_Military_Press": "Press militar sentado con barra",
 "Seated_Cable_Rows": "Remo en polea baja sentado",
 "Seated_Calf_Raise": "Gemelos sentado en máquina",
 "Seated_Dumbbell_Press": "Press de hombros sentado con mancuernas",
 "Seated_Leg_Curl": "Curl femoral sentado",
 "Seated_Triceps_Press": "Extensión de tríceps sentado con mancuerna",
 "Side_Lateral_Raise": "Elevaciones laterales",
 "Side_Bridge": "Plancha lateral",
 "Single_Leg_Glute_Bridge": "Puente de glúteo a una pierna",
 "Sit-Up": "Abdominales (sit-up)",
 "Skating": "Patinaje",
 "Sled_Push": "Empuje de trineo",
 "Smith_Machine_Bench_Press": "Press de banca en multipower",
 "Smith_Machine_Squat": "Sentadilla en multipower",
 "Smith_Machine_Behind_the_Back_Shrug": "Encogimientos en multipower",
 "Smith_Machine_Calf_Raise": "Gemelos en multipower",
 "Smith_Machine_Incline_Bench_Press": "Press inclinado en multipower",
 "Split_Squat_with_Dumbbells": "Sentadilla búlgara con mancuernas",
 "Squats_-_With_Bands": "Sentadillas con bandas",
 "Stairmaster": "Escaladora",
 "Standing_Barbell_Calf_Raise": "Gemelos de pie con barra",
 "Standing_Calf_Raises": "Gemelos de pie en máquina",
 "Standing_Dumbbell_Press": "Press de hombros de pie con mancuernas",
 "Standing_Dumbbell_Triceps_Extension": "Extensión de tríceps de pie con mancuerna",
 "Standing_Military_Press": "Press militar de pie",
 "Standing_Overhead_Barbell_Triceps_Extension": "Extensión de tríceps sobre la cabeza con barra",
  "Stiff-Legged_Barbell_Deadlift": "Peso muerto piernas rígidas",
 "Straight-Arm_Dumbbell_Pullover": "Pullover con mancuerna brazos rectos",
 "Sumo_Deadlift": "Peso muerto sumo",
 "T-Bar_Row_with_Handle": "Remo en T con agarre",
 "Trap_Bar_Deadlift": "Peso muerto con barra hexagonal",
 "Triceps_Pushdown": "Extensión de tríceps en polea",
 "Triceps_Pushdown_-_Rope_Attachment": "Extensión de tríceps en polea con cuerda",
 "Triceps_Pushdown_-_V-Bar_Attachment": "Extensión de tríceps en polea con barra V",
 "Upright_Barbell_Row": "Remo al mentón con barra",
 "Upright_Cable_Row": "Remo al mentón en polea",
 "Weighted_Pull_Ups": "Dominadas lastradas",
 "Wide-Grip_Lat_Pulldown": "Jalón al pecho agarre ancho",
 "Wide-Grip_Pulldown_Behind_The_Neck": "Jalón tras nuca",
 "Wide-Grip_Rear_Pull-Up": "Dominadas agarre ancho",
 "Wide-Grip_Standing_Barbell_Curl": "Curl con barra agarre ancho",
 "Zercher_Squats": "Sentadilla Zercher",
 "Walking_Treadmill": "Caminar en cinta",
 "Step_Mill": "Escaladora (step mill)",
 "Bicycling": "Bicicleta",
 "Rope_Jumping": "Saltar a la comba",
 "Mountain_Climbers": "Escaladores (mountain climbers)",
 "Box_Jump_Multiple_Response": "Saltos al cajón",
 "Farmers_Walk": "Paseo del granjero",
 "Seated_Dumbbell_Curl": "Curl sentado con mancuernas",
 "Seated_Side_Lateral_Raise": "Elevaciones laterales sentado",
 "Smith_Machine_Bent_Over_Row": "Remo inclinado en multipower",
 "Smith_Machine_Overhead_Shoulder_Press": "Press de hombros en multipower",
 "Smith_Machine_Leg_Press": "Prensa en multipower",
 "Split_Squats": "Sentadilla búlgara",
 "Standing_Dumbbell_Calf_Raise": "Gemelos de pie con mancuernas",
 "Stiff-Legged_Dumbbell_Deadlift": "Peso muerto piernas rígidas con mancuernas",
 "Straight-Arm_Pulldown": "Pullover en polea brazos rectos",
 "Triceps_Overhead_Extension_with_Rope": "Extensión de tríceps sobre la cabeza con cuerda",
 "Two-Arm_Kettlebell_Military_Press": "Press militar con dos kettlebells",
 "Weighted_Crunches": "Crunch lastrado",
 "Weighted_Bench_Dip": "Fondos en banco lastrados",
 "Weighted_Squat": "Sentadilla lastrada",
 "Donkey_Calf_Raises": "Gemelos burro",
 "Trail_Running_Walking": "Trail running / senderismo",
 "Battling_Ropes": "Cuerdas de batalla",
 "Rope_Climb": "Subida de cuerda",
 "Vertical_Swing": "Swing vertical con mancuerna",
 "Sledgehammer_Swings": "Golpes de mazo",
 "Front_Box_Jump": "Salto frontal al cajón",
 "Lateral_Box_Jump": "Salto lateral al cajón",
}

CAT_MET = {
 "strength": 5.0, "powerlifting": 6.0, "olympic weightlifting": 6.0, "strongman": 8.0,
 "plyometrics": 8.0, "stretching": 2.3, "cardio": 7.0,
}
SPECIAL_MET = {
 "Running_Treadmill": 9.8, "Jogging_Treadmill": 7.0, "Walking_Treadmill": 3.8,
 "Bicycling_Stationary": 6.8, "Recumbent_Bike": 5.5, "Bicycling": 7.5,
 "Rowing_Stationary": 7.0, "Elliptical_Trainer": 5.0, "Stairmaster": 9.0, "Step_Mill": 9.0,
 "Rope_Jumping": 11.0, "Trail_Running_Walking": 6.0, "Battling_Ropes": 8.0, "Mountain_Climbers": 8.0, "Skating": 7.0, "Sled_Push": 8.0, "Farmers_Walk": 6.0,
}

out = []
missing = [k for k in ES if k not in {e['id'] for e in d}]
for e in d:
    out.append({
        "id": e["id"],
        "name": e["name"],
        "nameEs": ES.get(e["id"]),
        "category": e["category"],
        "equipment": e["equipment"] or "other",
        "level": e["level"],
        "mechanic": e.get("mechanic"),
        "force": e.get("force"),
        "primaryMuscles": e["primaryMuscles"],
        "secondaryMuscles": e["secondaryMuscles"],
        "instructions": e["instructions"],
        "images": e["images"],
        "met": SPECIAL_MET.get(e["id"], CAT_MET[e["category"]]),
    })
json.dump(out, open('exercises.json', 'w'), ensure_ascii=False, separators=(',', ':'))
print(len(out), "exercises;", sum(1 for o in out if o['nameEs']), "translated; missing ids:", missing)
